### ISSUE TITLE
Please update - Error on 2.1.55qt6 Beta 4 

### ISSUE THREAD

**Issue by DoctorToBeIn23** [hgiesel/anki_straight_reward#27]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (e3c3405f) Python 3.9.7 Qt 6.4.0 PyQt 6.4.0
Platform: macOS-11.5.2-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-12-03 20:06:19
Add-ons possibly involved: ⁨Straight Reward⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 556, in handler
  File "aqt.reviewer", line 532, in _onAnswerButton
  File "aqt.reviewer", line 431, in _answerCard
  File "aqt.hooks_gen", line 3807, in __call__
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/957961234/src/lib/review_hook.py", line 101, in <lambda>
    lambda ease_tuple, reviewer, card: on_will_answer_card(
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/957961234/src/lib/review_hook.py", line 85, in on_will_answer_card
    check_straight_reward(gains, reviewer, card, ease_tuple[1])
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/957961234/src/lib/review_hook.py", line 64, in check_straight_reward
    next_states = reviewer.get_next_states()
AttributeError: 'Reviewer' object has no attribute 'get_next_states'

Happens every time but only on the first card. It will not adjust the ease.

**Comment by DoctorToBeIn23** [comment]
This only occurs when V3 scheduler is on
